version: '3.7'

networks:
  default:
    name: jobs-network

volumes:
  postgres_data:
  pgadmin_data:
  metabase-data:

services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=jobs_database
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT=1
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "8080:80"
  metabase:
    image: metabase/metabase:latest
    depends_on:
      - pgdatabase
    ports:
      - "3000:3000"
    volumes:
      - metabase-data:/metabase-data
    # environment:
    # for metabase to store application data, default to JAVA H2 database named metabase.db
      # - MB_DB_TYPE=postgres
      # - MB_DB_DBNAME=metabase-data 
      # - MB_DB_PORT=5432
      # - MB_DB_USER=root
      # - MB_DB_PASS=root
      # - MB_DB_HOST=pgdatabase
    restart: on-failure
    # tty: true

